name: Deploy dev branch

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string 

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ vars[format('{0}_AWS_ACCESS_KEY_ID', 'C1')] }}
          aws-secret-access-key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', 'C1')] }}
          aws-region: eu-west-1
      - name: Say OK
        run: |
          echo " OK "
 
