  name: Deploy Lambda Function
  on:
    workflow_dispatch:
      inputs:
        customer:
          description: "Customer:"
          required: true
          default: "C8"
          type: choice
          options:
            - C8
            - C11
        environment:
          description: "Environment:"
          required: true
          default: "DEV"
          type: choice
          options:
            - DEV
            - ACC
        target-aws-lambda-function:
          required: true
          description: "Target AWS Lambda Function:"
          type: string 
        region:
          required: true
          description: "Target region:"
          type: string 

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:

        - name: "Print options"
          run: |
            echo "custumer-env-name=${{ inputs.CUSTOMER }}_${{ inputs.environment }}" >> $GITHUB_ENV

        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Replace Env
          run: |
            env=${{ inputs.environment }}
            filename=${{ inputs.CUSTOMER }}.json 
            sed -i -e "s/#ENV/${env,,}/g" config/${filename,,}
            mv config/${filename,,} config.json

        - uses: aws-actions/configure-aws-credentials@v4 
          with:
            aws-access-key-id: ${{ vars[format('{0}_AWS_ACCESS_KEY_ID', env.custumer-env-name)] }}
            aws-secret-access-key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.custumer-env-name)] }}
            aws-region: eu-west-1
        
        - name: Zip Files
          run: zip -r aws_lambda.zip ./

        - name: Update Lambda
          run:  |
            ls -la
            # Update Lambda function code
            pwd
            aws lambda update-function-code \
            --function-name testGitHubActionsDeploy \
            --zip-file fileb://./aws_lambda.zip  \
            --region eu-west-1
