  name: Deploy Lambda Function
  on:
    workflow_dispatch:
      inputs:
        customer: 
          description: "Customer"
          required: true
          default: "Client1"
          type: choice
          options:
            - Client1
            - Client2
        env:
          description: "Environment"
          required: true
          type: choice
          options:
            - DEV
            - ACC


  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:

        - name: "Print options"
          run: |
            echo "Customer: $CUSTOMER"
            echo "Environment: $ENVIRONMENT"
          env:
            CUSTOMER: ${{ inputs.customer }}
            ENVIRONMENT: ${{ inputs.env }} 

        - name: Prepare repo directory
          run: |
              mkdir -p ./lambda-code
              cd ./lambda-code

        - name: Checkout Repository
          uses: actions/checkout@v2

        
      
        - name: List artefact files with their timestamps to show that builds/downloads succeeded
          run: ls -lha
        - name: Install aws cli using pip3
          run: pip3 install awscli

        - name: Configure AWS credentials
          uses: ./.github/workflows/c1_dev_cred.yml

        - name: Zip Files
          run: zip -r aws_lambda.zip ./

        - name: Update Lambda
          run:  |
            ls -la
            # Update Lambda function code
            pwd
            aws lambda update-function-code \
            --function-name testGitHubActionsDeploy \
            --zip-file fileb://./aws_lambda.zip  \
            --region eu-west-1