
name: Deploy with Reusable file
on:
  workflow_dispatch:
    inputs:
      target-aws-lambda-function:
        required: true
        description: Target AWS Lambda Function
        type: choice
        options:
          - testGitHubActionsDeploy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Testing external file"
  deploy:
    uses: ./.github/workflows/upload-artefact.yml
    
    