  name: deploy to lambda
  on:
    workflow_dispatch:
    push:
      branches:
        - main
      paths:
        - '**.py'
  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Prepare repo directory
          run: |
              mkdir -p ./lambda-code
              cd ./lambda-code

        - name: Checkout Repository
          uses: actions/checkout@v2

        - name: Setup AWS CLI
          uses: aws-actions/configure-aws-credentials@master
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1 
      
        - name: List artefact files with their timestamps to show that builds/downloads succeeded
          run: ls -lha
        - name: Install aws cli using pip3
          run: pip3 install awscli
        - name: Configure AWS credentials
          run: aws configure set aws_access_key_id ${{ vars.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        - name: Upload artefacts to AWS S3
          run: |
            # Constants
            S3_BUCKET=tinyflix-2024-03-06
            S3_KEY=prognos_lambda.zip
            LAMBDA_FUNCTION_NAME=tinyflix_function

            echo "Uploading files to S3"
            aws s3 cp af/app/emr.py s3://tinyflix-2024-03-06/here-is-my-code/
            aws s3 cp af/app/config.py s3://tinyflix-2024-03-06/here-is-my-code/
            aws s3 cp af/main.py s3://tinyflix-2024-03-06/here-is-my-code/
            echo "Upload finished!"
    
        - name: Zip Files
          run:  |
            zip -r af prognos_lambda.zip .
            ls -la
            # Update Lambda function code
            aws lambda update-function-code --function-name tinyflix_function --s3-bucket $S3_BUCKET/here-is-my-code/ --s3-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}