  name: Deploy Lambda Function
  on:
    workflow_dispatch:
      inputs:
        customer: 
          description: "Customer"
          required: true
          default: "C1"
          type: choice
          options:
            - C1
            - C2
        environment:
          description: "Environment"
          required: true
          default: "DEV"
          type: choice
          options:
            - DEV
            - ACC

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:

        - name: "Print options"
          run: |
            echo "custumer-env-name=${{ inputs.CUSTOMER }}_${{ inputs.environment }}" >> $GITHUB_ENV

        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Replace Env
          run: |
            env=${{ inputs.environment }}
            filename=${{ inputs.CUSTOMER }}.json
            echo ${filename,,}
            sed -i -e 's/#ENV/$env/g' config/$filename

        - uses: aws-actions/configure-aws-credentials@v4 
          with:
            aws-access-key-id: ${{ vars[format('{0}_AWS_ACCESS_KEY_ID', env.custumer-env-name)] }}
            aws-secret-access-key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.custumer-env-name)] }}
            aws-region: eu-west-1
        
        - name: Zip Files
          run: zip -r aws_lambda.zip ./

        - name: Update Lambda
          run:  |
            ls -la
            # Update Lambda function code
            pwd
            aws lambda update-function-code \
            --function-name testGitHubActionsDeploy \
            --zip-file fileb://./aws_lambda.zip  \
            --region eu-west-1