  name: Deploy Lambda Function
  on:
    workflow_dispatch:
      inputs:
        customer: 
          description: "Customer"
          required: true
          default: "Client1"
          type: choice
          options:
            - C1
            - C2
        env:
          description: "Environment"
          required: true
          type: choice
          options:
            - DEV
            - ACC


  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:

        - name: "Print options"
          run: |
            echo "Customer: $CUSTOMER"
            echo "Environment: $ENVIRONMENT"
          env:
            CUSTOMER: ${{ inputs.customer }}
            ENVIRONMENT: ${{ inputs.env }} 
        
        - run: |
            accesskey=${{ inputs.customer }}_${{ inputs.env }}_AWS_ACCESS_KEY_ID"
            echo ${{ secrets[format('{0}_A',  ${accesskey})] }}

        - name: Prepare repo directory
          run: |
              mkdir -p ./lambda-code
              cd ./lambda-code

        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - uses: aws-actions/configure-aws-credentials@v4
          if: ${{ inputs.customer == 'C1' &&  inputs.env == 'dev' }}
          with:
            aws-access-key-id: ${{ vars.C1_DEV_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.C1_DEV_AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-1

        - uses: aws-actions/configure-aws-credentials@v4
          if: ${{ inputs.customer == 'C2' &&  inputs.env == 'dev' }}
          with:
            aws-access-key-id: ${{ vars.C2_DEV_AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.C2_DEV_AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-1
        
        - name: Zip Files
          run: zip -r aws_lambda.zip ./

        - name: Update Lambda
          run:  |
            ls -la
            # Update Lambda function code
            pwd
            aws lambda update-function-code \
            --function-name testGitHubActionsDeploy \
            --zip-file fileb://./aws_lambda.zip  \
            --region eu-west-1