  name: deploy to lambda
  on:
    push:
      branches:
        - main
      paths:
        - '**.py'
  jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Prepare repo directory
          run: |
              mkdir -p ./lambda-code
              cd ./lambda-code

        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

        - name: Setup AWS CLI
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2 # Modify this to your desired AWS region

        - name: List artefact files with their timestamps to show that builds/downloads succeeded
          run: ls -al ./lambda-code
        - name: Install aws cli using pip3
          run: pip3 install awscli
        - name: Configure AWS credentials
          run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_ACCESS_KEY }} && aws configure set default.region us-west-2
        - name: Upload artefacts to AWS S3
          run: |
            echo "Uploading artefacts to S3"
            aws s3 cp ./*.py s3://tinyflix-2024-03-06/here-is-my-code/
            echo "Artefacts uploaded to S3"