  name: Deploy Lambda Function
  on:
    workflow_dispatch:
      inputs:
        customer: 
          description: "Customer"
          required: true
          default: "C1"
          type: choice
          options:
            - NBT
            - VA
        environment:
          description: "Environment"
          required: true
          default: "DEV"
          type: choice
          options:
            - DEV
            - ACC

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Replace Env  
          run: |
            CUSTOMER_NAME=${{ inputs.customer }} 
            AWS_ENV=""
            if [ ${{ inputs.environment }} == "DEV" ] || [ ${{ inputs.environment }} == "ACC" ]; then
              AWS_ENV="NoProd"
            else
              AWS_ENV="Prod"
            fi
            echo "env: ${AWS_ENV} "

            # Query on customers.json
            CUSTOMER_CODE=$(jq -r --arg CUSTOMER_NAME "$CUSTOMER_NAME" --arg ENV_KEY "$AWS_ENV" '.customers[] | select(.name==$CUSTOMER_NAME) | .codes[$ENV_KEY]' config/customers.json)
 
            # Write customer code and Env to GH-Env
            echo "custumer_code_env=${CUSTOMER_CODE}_${{ inputs.environment }}" >> $GITHUB_ENV

            env=${{ inputs.environment }}
            filename="${CUSTOMER_CODE}.json"

            sed -i  "s/#ENV/${env,,}/g;s/#CUSTOMER/${CUSTOMER_CODE,,}/g" config/${filename,,}
            mv config/${filename,,} config.json
            rm -rf ./config/

        - uses: aws-actions/configure-aws-credentials@v4 
          with:
            aws-access-key-id: ${{ vars[format('{0}_AWS_ACCESS_KEY_ID', env.custumer_code_env)] }}
            aws-secret-access-key: ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.custumer_code_env)] }}
            aws-region: eu-west-1
        
        - name: Zip Files
          run: zip -r aws_lambda.zip ./

        - name: Update Lambda
          run:  |
            ls -la
            # Update Lambda function code
            pwd
            aws lambda update-function-code \
            --function-name testGitHubActionsDeploy \
            --zip-file fileb://./aws_lambda.zip  \
            --region eu-west-1